import { FC, useEffect, useRef } from 'react'
import { useStoreon } from 'storeon/react'
import Head from 'next/head'
import {
	Container,
	Button,
	Drawer,
	DrawerBody,
	DrawerHeader,
	DrawerOverlay,
	DrawerContent,
	DrawerCloseButton,
	useDisclosure,
} from "@chakra-ui/react"
import { CurrencyActions } from '../../store/currency'
import { Actions } from '../../store/products'
import { Products } from '../Products/Products'
import { Cart } from '../Cart/Cart'

export const HomePage: FC<{}> = () => {
	const { dispatch } = useStoreon();

	const { isOpen, onOpen, onClose } = useDisclosure();
	const btnRef = useRef();

	useEffect(() => {
		dispatch(Actions.fetchNames);
		dispatch(Actions.subscribe);
		dispatch(CurrencyActions.subscribe);
	}, []);

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header>
				<Container position="sticky" top="0" marginBottom="20px" marginTop="20px">
					<Button ref={btnRef} colorScheme="teal" onClick={onOpen}>
						Корзина
					</Button>
				</Container>
			</header>
			<main>
				<Container>
					<Products />
				</Container>
			</main>
			<Drawer
				isOpen={isOpen}
				placement="right"
				size="full"
				onClose={onClose}
				finalFocusRef={btnRef}
			>
				<DrawerOverlay>
					<DrawerContent>
					<DrawerCloseButton />
					<DrawerHeader>Корзина</DrawerHeader>

					<DrawerBody>
						<Cart />
					</DrawerBody>

					</DrawerContent>
				</DrawerOverlay>
			</Drawer>
		</div>
	)
}
